apiVersion: v1
kind: Secret
metadata:
  name: mongo-db-creds
type: Opaque
stringData:
  config.yaml: |
    MONGO_URI: "https://my.api.com/api/v1"
    MONGO_USERNAME: "admin"
    MONGO_PASSWORD: "qwdf45ty"    